import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
const source=readFileSync(new URL('../extension/content.js',import.meta.url),'utf8');
const tick=()=>new Promise(r=>setTimeout(r,20));
const row=id=>`<tr id="trPos0"><td><input type="checkbox" id="chkInfraItem${id}"></td><td data-label="Seq.">${id}</td><td data-label="Processo"><a href="?id_procedimento=${id}">Processo fictício</a></td><td data-label="Tipo">Tipo fictício</td><td data-label="Anotações">Anotação nativa</td><td data-label="Ações"><a href="#">Anotações</a></td></tr>`;
function fixture(action='rel_bloco_protocolo_listar',origin='bloco_interno_listar'){
 const dom=new JSDOM(`<a id="lnkUsuarioSistema" title="Pessoa Teste (teste/SEPM)" href="?infra_unidade_atual=1"></a><form id="frmRelBlocoProtocoloLista"><div id="divInfraAreaPaginacaoSuperior"></div><div id="divInfraAreaTabela"><table id="tblProtocolosBlocos"><tr><th></th><th>Seq.</th><th>Processo</th><th>Tipo</th><th>Anotações</th><th>Ações</th></tr>${row('100')}${row('200')}</table></div><button id="native" type="button">Original</button></form>`,{url:`https://sei.rj.gov.br/sei/controlador.php?acao=${action}&acao_origem=${origin}&id_bloco=2`,runScripts:'outside-only'});
 let offline=false;const calls=[];dom.window.chrome={runtime:{sendMessage:async msg=>{calls.push(msg);if(msg.history)return {data:['create','delete','assign','unassign','rename','undo'].map(type=>({version:1,time:'2026-10-01T12:00:00Z',actor:{login:'teste'},action:{type,tabName:'Assunto',processIds:['100']}}))};return offline?{error:'Falha simulada'}:{data:{version:1,tabs:[{id:'a',name:'Assunto'}],assignments:{'100':['a']}}};}}};
 dom.window.eval(readFileSync(new URL('../extension/history.js',import.meta.url),'utf8'));dom.window.eval(readFileSync(new URL('../extension/theme.js',import.meta.url),'utf8'));dom.window.eval(source);return {dom,calls,disconnect:()=>{offline=true;}};
}
test('retorno nativo de exclusão mantém inicialização, colunas e cabeçalho sem aceitar outras origens',async()=>{
 const f=fixture('rel_bloco_protocolo_listar','rel_bloco_protocolo_excluir');try{await tick();const d=f.dom.window.document;assert.ok(d.querySelector('#sei-organizador'));assert.equal(d.querySelector('[data-tab=general]').getAttribute('aria-selected'),'true');assert.equal(d.querySelectorAll('th[data-so-column]').length,2);assert.equal(d.querySelectorAll('.so-floating-header').length,8);assert.equal(d.querySelectorAll('.so-copy-number').length,2);assert.ok(f.calls.length>0);}finally{f.dom.window.close();}
 const unrelated=fixture('rel_bloco_protocolo_listar','bloco_assinatura_listar');try{await tick();assert.equal(unrelated.dom.window.document.querySelector('#sei-organizador'),null);assert.equal(unrelated.calls.length,0);}finally{unrelated.dom.window.close();}
});
test('colunas próprias idempotentes, múltiplos assuntos, novas linhas e estado desconhecido',async()=>{
 const f=fixture();try{await tick();const w=f.dom.window,d=w.document,t=d.querySelector('table');const first=d.querySelector('#chkInfraItem100').closest('tr');
 let state={version:2,tabs:[{id:'a',name:'Assunto'},{id:'b',name:'Outra'},{id:'c',name:'<Terceira>'}],assignments:{100:['a','b','c']},statuses:{100:'follow'}};
 w.chrome.runtime.sendMessage=async()=>({data:state});const click=name=>Array.from(d.querySelectorAll('#sei-organizador button')).find(b=>b.textContent===name).click();click('Atualizar');await tick();
 assert.deepEqual(Array.from(t.rows[0].cells).map(c=>c.textContent),['','Seq.','Processo','Tipo','Assunto','Status','Anotações','Ações']);
 assert.equal(first.cells.length,8);assert.equal(first.querySelector('[data-so-column=subject]').textContent,'Assuntomais 2');assert.match(first.querySelector('[data-so-column=subject]').getAttribute('aria-label'),/<Terceira>/);assert.equal(first.querySelector('[data-so-column=subject] terceira'),null);
 const note=first.querySelector('[data-label="Anotações"]'),nativeAction=first.querySelector('[data-label="Ações"] a');assert.equal(note.textContent,'Anotação nativa');assert.equal(note.querySelector('button'),null);assert.match(first.querySelector('[data-so-column=status]').textContent,/Acompanhar/);
 let nativeClicks=0;nativeAction.addEventListener('click',()=>nativeClicks++);nativeAction.click();assert.equal(nativeClicks,1);
 t.insertAdjacentHTML('beforeend',row('300')+'<tr><td colspan="6">Paginação nativa</td></tr>');await tick();click('Atualizar');await tick();assert.equal(t.querySelectorAll('th[data-so-column]').length,2);assert.equal(d.querySelector('#chkInfraItem300').closest('tr').cells.length,8);assert.equal(t.querySelector('[colspan]').colSpan,8);assert.equal(t.querySelectorAll('.so-status-marker').length,3);
 click('Assunto');assert.equal(d.querySelector('.so-viewing').textContent,'Visualizando: Assunto');assert.equal(d.querySelector('[data-tab=general]').getAttribute('aria-selected'),'false');click('Geral');assert.equal(d.querySelector('.so-viewing').textContent,'Visualizando: todos os processos');assert.equal(first.querySelector('[data-so-column=subject]').textContent,'Assuntomais 2');
 w.chrome.runtime.sendMessage=async()=>({error:'Offline'});click('Atualizar');await tick();assert.equal(first.querySelector('[data-so-column=subject]').textContent,'Não sincronizado');assert.match(first.querySelector('[data-so-column=status]').textContent,/indisponível/);assert.equal(d.querySelector('[data-tab=general]').getAttribute('aria-selected'),'true');assert.equal(nativeAction.isConnected,true);
 }finally{f.dom.window.close();}
});
test('cabeçalho original acompanha altura da barra e limite da tabela sem duplicar controles',async()=>{
 const f=fixture();try{await tick();const w=f.dom.window,d=w.document,t=d.querySelector('table'),header=t.rows[0],root=d.querySelector('#sei-organizador');
 const all=d.createElement('input');all.type='checkbox';all.id='native-select-all';header.cells[0].append(all);let clicks=0;all.addEventListener('click',()=>clicks++);
 let barBottom=120,tableTop=-300,tableBottom=1000;root.getBoundingClientRect=()=>({bottom:barBottom});t.getBoundingClientRect=()=>({top:tableTop,bottom:tableBottom});header.getBoundingClientRect=()=>({height:30});Object.defineProperty(header,'offsetTop',{value:0});
 const recalc=async()=>{w.dispatchEvent(new w.Event('scroll'));await tick();};await recalc();assert.equal(t.style.getPropertyValue('--so-table-header-shift'),'420px');
 barBottom=160;w.dispatchEvent(new w.Event('resize'));await tick();assert.equal(t.style.getPropertyValue('--so-table-header-shift'),'460px');
 tableBottom=180;await recalc();assert.equal(t.style.getPropertyValue('--so-table-header-shift'),'450px');tableTop=200;tableBottom=900;await recalc();assert.equal(t.style.getPropertyValue('--so-table-header-shift'),'0px');
 assert.equal(t.rows[0],header);assert.equal(d.querySelectorAll('#native-select-all').length,1);assert.equal(header.querySelectorAll('.so-floating-header').length,8);all.click();assert.equal(clicks,1);assert.equal(all.checked,true);
 }finally{f.dom.window.close();}
});
test('Geral, seleção oculta, linhas de outra página, privacidade e indisponibilidade',async()=>{
 const f=fixture();try{await tick();const d=f.dom.window.document;const buttons=()=>Array.from(d.querySelectorAll('#sei-organizador button'));const click=name=>buttons().find(b=>b.textContent===name).click();
 assert.ok(d.querySelector('#sei-organizador'));assert.equal(d.querySelector('#native').textContent,'Original');
 d.querySelector('#chkInfraItem200').checked=true;click('Assunto');assert.equal(d.querySelector('#chkInfraItem200').checked,false);assert.equal(d.querySelector('#chkInfraItem200').closest('tr').hidden,true);
 click('Geral');assert.equal(d.querySelector('#chkInfraItem200').closest('tr').hidden,false);
 click('Assunto');d.querySelector('#tblProtocolosBlocos').insertAdjacentHTML('beforeend',row('300'));await tick();assert.equal(d.querySelector('#chkInfraItem300').closest('tr').hidden,true);
 f.disconnect();click('Atualizar');await tick();assert.equal(d.querySelector('#chkInfraItem300').closest('tr').hidden,false);assert.ok(Array.from(d.querySelectorAll('[role=status]')).some(e=>/Sem sincronização/.test(e.textContent)));assert.equal(buttons().find(b=>b.textContent==='+ Criar assunto').disabled,true);
 assert.ok(f.calls.every(c=>Object.keys(c).every(k=>['type','unit','block'].includes(k))));
 }finally{f.dom.window.close();}
});
test('não injeta no Controle de Processos',()=>{const f=fixture('procedimento_controlar');try{assert.equal(f.dom.window.document.querySelector('#sei-organizador'),null);assert.equal(f.calls.length,0);}finally{f.dom.window.close();}});
test('menu atribui somente alvo, mantém seleção alheia e respeita links/offline',async()=>{
 const f=fixture();try{await tick();const w=f.dom.window,d=w.document;const target=d.querySelector('#chkInfraItem200').closest('tr');const other=d.querySelector('#chkInfraItem100');other.checked=true;
 const open=element=>{const e=new w.MouseEvent('contextmenu',{bubbles:true,cancelable:true,clientX:9999,clientY:9999});element.dispatchEvent(e);return e;};
 assert.equal(open(target.querySelector('a')).defaultPrevented,false);assert.equal(d.querySelector('[role=menu]'),null);
 assert.equal(open(target).defaultPrevented,true);assert.ok(d.querySelector('[role=menu]'));assert.equal(d.activeElement.getAttribute('role'),'menuitemcheckbox');d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(d.querySelector('[role=menu]'),null);
 target.dispatchEvent(new w.KeyboardEvent('keydown',{key:'F10',shiftKey:true,bubbles:true,cancelable:true}));assert.ok(d.querySelector('[role=menu]'));w.dispatchEvent(new w.Event('scroll'));assert.equal(d.querySelector('[role=menu]'),null);
 open(target);d.querySelector('#native').dispatchEvent(new w.Event('pointerdown',{bubbles:true}));assert.equal(d.querySelector('[role=menu]'),null);
 open(target);d.querySelector('[role=menuitemcheckbox]').click();await tick();const op=f.calls.find(c=>c.body);assert.deepEqual(Array.from(op.body.action.processIds),['200']);assert.equal(other.checked,true);assert.equal(d.querySelector('[role=menu]'),null);
 f.disconnect();Array.from(d.querySelectorAll('#sei-organizador button')).find(b=>b.textContent==='Atualizar').click();await tick();assert.equal(open(target).defaultPrevented,false);assert.equal(d.querySelector('[role=menu]'),null);
 }finally{f.dom.window.close();}
});
test('histórico aplica cores por ação e mantém rótulos textuais',async()=>{
 const f=fixture();try{await tick();const d=f.dom.window.document;Array.from(d.querySelectorAll('button')).find(b=>b.textContent==='Histórico').click();await tick();for(const type of ['create','delete','assign','unassign','rename','undo'])assert.ok(d.querySelector('.so-history-'+type)?.textContent.includes('teste'));assert.equal(d.querySelectorAll('.so-history-entry').length,6);}finally{f.dom.window.close();}
});
test('menu reflete múltiplos vínculos e retira somente processo alvo',async()=>{
 const f=fixture();try{await tick();const w=f.dom.window,d=w.document;let state={version:2,tabs:[{id:'a',name:'Assunto'},{id:'b',name:'Outra'},{id:'c',name:'Livre'}],assignments:{100:['a','b'],200:['a']}};
 w.chrome.runtime.sendMessage=async msg=>{f.calls.push(msg);if(msg.body){const op=msg.body.action;assert.equal(op.type,'unassign');assert.equal(op.tabId,'b');assert.deepEqual(Array.from(op.processIds),['100']);state={...state,version:3,assignments:{100:['a'],200:['a']}};}return {data:state};};
 Array.from(d.querySelectorAll('button')).find(b=>b.textContent==='Atualizar').click();await tick();d.querySelector('#chkInfraItem200').checked=true;const target=d.querySelector('#chkInfraItem100').closest('tr');
 const open=()=>target.dispatchEvent(new w.MouseEvent('contextmenu',{bubbles:true,cancelable:true}));open();let entries=Array.from(d.querySelectorAll('[role=menuitemcheckbox]'));assert.deepEqual(entries.map(b=>b.getAttribute('aria-checked')),['true','true','false']);assert.match(entries[0].textContent,/Retirar de Assunto/);assert.match(entries[2].textContent,/Atribuir a Livre/);
 d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));Array.from(d.querySelectorAll('[role=tab]')).find(b=>b.textContent==='Outra').click();open();entries=Array.from(d.querySelectorAll('[role=menuitemcheckbox]'));entries[1].click();await tick();assert.equal(d.querySelector('#chkInfraItem200').checked,false);assert.equal(target.hidden,true);Array.from(d.querySelectorAll('[role=tab]')).find(b=>b.textContent==='Geral').click();assert.equal(target.hidden,false);assert.equal(d.querySelector('[role=menu]'),null);open();entries=Array.from(d.querySelectorAll('[role=menuitemcheckbox]'));assert.deepEqual(entries.map(b=>b.getAttribute('aria-checked')),['true','false','false']);assert.match(entries[1].textContent,/Atribuir a Outra/);assert.deepEqual(state.assignments[200],['a']);
 }finally{f.dom.window.close();}
});
test('Sem assunto virtual, contagens locais, vínculos obsoletos, sincronização e offline',async()=>{
 const f=fixture();try{await tick();const w=f.dom.window,d=w.document;let state={version:2,tabs:[{id:'a',name:'Assunto'},{id:'b',name:'Outra'}],assignments:{100:['a','b'],200:['obsoleta']}};
 w.chrome.runtime.sendMessage=async msg=>{f.calls.push(msg);if(msg.body){const op=msg.body.action;const remaining=(state.assignments[op.processIds[0]]||[]).filter(id=>id!==op.tabId);state={...state,version:state.version+1,assignments:{...state.assignments,[op.processIds[0]]:remaining}};}return {data:state};};
 const click=name=>Array.from(d.querySelectorAll('#sei-organizador button')).find(b=>b.textContent===name).click();const tab=name=>Array.from(d.querySelectorAll('[role=tab]')).find(b=>b.textContent===name);
 click('Atualizar');await tick();assert.equal(tab('Geral').getAttribute('aria-selected'),'true');assert.equal(tab('Geral').dataset.count,undefined);assert.equal(tab('Assunto').dataset.count,'1');assert.equal(tab('Outra').dataset.count,'1');assert.equal(tab('Sem assunto').dataset.count,'1');
 d.querySelector('#chkInfraItem100').checked=true;click('Sem assunto');assert.equal(d.querySelector('#chkInfraItem100').checked,false);assert.equal(d.querySelector('#chkInfraItem100').closest('tr').hidden,true);assert.equal(d.querySelector('#chkInfraItem200').closest('tr').hidden,false);assert.equal(Array.from(d.querySelectorAll('button')).some(b=>b.textContent==='Renomear'),false);assert.equal(d.querySelectorAll('.so-toolbar select').length,0);assert.equal(d.querySelector('.so-filter-notice'),null);assert.match(tab('Geral').title,/Mostrar todos/);
 d.querySelector('table').insertAdjacentHTML('beforeend',row('300'));await tick();assert.equal(tab('Geral').dataset.count,undefined);assert.equal(tab('Sem assunto').dataset.count,'2');assert.equal(d.querySelector('#chkInfraItem300').closest('tr').hidden,false);
 click('Geral');assert.equal(d.querySelectorAll('tr[hidden]').length,0);const target=d.querySelector('#chkInfraItem100').closest('tr');const open=()=>target.dispatchEvent(new w.MouseEvent('contextmenu',{bubbles:true,cancelable:true}));open();Array.from(d.querySelectorAll('[role=menuitemcheckbox]')).find(b=>b.textContent.includes('Assunto')).click();await tick();assert.equal(tab('Sem assunto').dataset.count,'2');open();Array.from(d.querySelectorAll('[role=menuitemcheckbox]')).find(b=>b.textContent.includes('Outra')).click();await tick();assert.equal(tab('Sem assunto').dataset.count,'3');click('Sem assunto');assert.equal(target.hidden,false);
 w.chrome.runtime.sendMessage=async()=>({error:'Falha simulada'});click('Atualizar');await tick();assert.equal(tab('Geral').getAttribute('aria-selected'),'true');assert.equal(tab('Sem assunto').disabled,true);assert.equal(tab('Sem assunto').dataset.count,'—');assert.match(d.querySelector('.so-summary').textContent,/classificações desconhecidas/);assert.equal(d.querySelectorAll('tr[hidden]').length,0);
 }finally{f.dom.window.close();}
});
test('histórico alterna, preserva estado após sync e ignora respostas atrasadas',async()=>{
 const f=fixture();try{await tick();const d=f.dom.window.document;const click=name=>Array.from(d.querySelectorAll('button')).find(b=>b.textContent===name).click();const toggle=()=>d.querySelector('[aria-controls="so-history-panel"]');const panel=d.querySelector('#so-history-panel');
 click('Histórico');await tick();assert.equal(toggle().getAttribute('aria-expanded'),'true');assert.equal(panel.hidden,false);click('Atualizar');await tick();assert.equal(toggle().getAttribute('aria-expanded'),'true');assert.equal(toggle().textContent,'Fechar histórico');assert.equal(panel.querySelectorAll('button').length,0);click('Fechar histórico');assert.equal(panel.hidden,true);click('Histórico');await tick();assert.equal(panel.hidden,false);click('Fechar histórico');assert.equal(toggle().getAttribute('aria-expanded'),'false');click('Atualizar');await tick();assert.equal(panel.hidden,true);
 let resolve,count=0;const original=f.dom.window.chrome.runtime.sendMessage;f.dom.window.chrome.runtime.sendMessage=msg=>msg.history?(count++,new Promise(r=>{resolve=r;})):original(msg);
 click('Histórico');click('Fechar histórico');resolve({data:[]});await tick();assert.equal(panel.hidden,true);assert.equal(panel.children.length,0);assert.equal(toggle().getAttribute('aria-expanded'),'false');
 click('Histórico');click('Fechar histórico');click('Histórico');assert.equal(count,2);resolve({data:[]});await tick();assert.equal(panel.hidden,false);assert.equal(panel.querySelectorAll('button').length,0);assert.equal(toggle().textContent,'Fechar histórico');assert.ok(!panel.textContent.includes('Carregando'));
 }finally{f.dom.window.close();}
});
test('copiar usa somente número do link, preserva controles e não duplica em mutações',async()=>{
 const f=fixture();try{await tick();const w=f.dom.window,d=w.document;const link=d.querySelector('a[href*="id_procedimento=100"]');link.textContent='  SEI-123456/123456/2026 \n ';const values=[];Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async value=>{values.push(value);}},configurable:true});
 const copy=link.nextElementSibling;assert.equal(copy.type,'button');assert.equal(copy.getAttribute('aria-label'),'Copiar número do processo');d.querySelector('#chkInfraItem100').checked=true;let bubbled=0;link.closest('tr').addEventListener('click',()=>bubbled++);copy.click();await tick();assert.deepEqual(values,['SEI-123456/123456/2026']);assert.equal(bubbled,0);assert.equal(d.querySelector('#chkInfraItem100').checked,true);assert.equal(copy.nextElementSibling.textContent,'Copiado');assert.equal(d.querySelector('[role=menu]'),null);
 Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async()=>{throw new Error('Denied');}},configurable:true});copy.click();await tick();assert.match(copy.nextElementSibling.textContent,/Não foi possível copiar/);assert.ok(!copy.nextElementSibling.textContent.includes('Copiado'));
 d.querySelector('table').insertAdjacentHTML('beforeend',row('300'));await tick();assert.equal(d.querySelectorAll('.so-copy-number').length,3);Array.from(d.querySelectorAll('button')).find(b=>b.textContent==='Atualizar').click();await tick();assert.equal(d.querySelectorAll('.so-copy-number').length,3);assert.equal(d.querySelectorAll('.so-copy-feedback').length,3);assert.equal(link.textContent.trim(),'SEI-123456/123456/2026');
 }finally{f.dom.window.close();}
});
test('status na coluna própria: manual, alvo correto, sync, sem assunto e offline',async()=>{
 const f=fixture();try{await tick();const w=f.dom.window,d=w.document;const target=d.querySelector('#chkInfraItem200').closest('tr');target.querySelector('[data-label="Anotações"]').innerHTML='<span id="note">Anotação preservada</span>';target.querySelector('[data-label="Ações"] a').id='native-note';
 let state={version:2,tabs:[{id:'a',name:'Assunto'}],assignments:{100:['a']},statuses:{}};w.chrome.runtime.sendMessage=async msg=>{f.calls.push(msg);if(msg.body){const a=msg.body.action;assert.equal(a.type,'status');assert.deepEqual(Array.from(a.processIds),['200']);state={...state,version:3,statuses:{200:a.status}};}return {data:state};};
 const click=name=>Array.from(d.querySelectorAll('#sei-organizador button')).find(b=>b.textContent===name).click();click('Atualizar');await tick();let marker=target.querySelector('.so-status-marker');assert.ok(marker.textContent.includes('Sem status'));marker.click();const option=Array.from(d.querySelectorAll('[role=menuitemradio]')).find(b=>b.textContent.includes('Urgente'));assert.ok(option);option.click();await tick();assert.match(marker.textContent,/Urgente/);assert.equal(d.querySelector('#note').textContent,'Anotação preservada');assert.ok(d.querySelector('#native-note'));click('Sem assunto');assert.equal(target.hidden,false);assert.equal(target.querySelectorAll('.so-status-marker').length,1);
 state={...state,version:4,statuses:{200:'follow'}};click('Atualizar');await tick();assert.match(marker.textContent,/Acompanhar/);w.chrome.runtime.sendMessage=async()=>({error:'Falha simulada'});click('Atualizar');await tick();assert.match(marker.textContent,/Status indisponível/);assert.equal(marker.disabled,true);assert.equal(target.hidden,false);
 }finally{f.dom.window.close();}
});
test('toolbar mantém todos comandos visíveis e histórico separado da barra sticky',async()=>{
 const f=fixture();try{await tick();const d=f.dom.window.document;assert.equal(d.querySelector('.so-options'),null);const toolbar=d.querySelector('.so-toolbar');for(const label of ['+ Criar assunto','Histórico','Desfazer última alteração','Atualizar'])assert.ok(Array.from(toolbar.querySelectorAll('button')).some(b=>b.textContent===label));assert.equal(toolbar.querySelector('select'),null);assert.ok(!toolbar.textContent.includes('Atribuir selecionados'));assert.ok(!toolbar.textContent.includes('Retirar classificação'));assert.ok(!d.querySelector('#sei-organizador').contains(d.querySelector('#so-history-panel')));assert.equal(d.querySelector('#sei-organizador').style.getPropertyValue('--so-sticky-top'),'0px');
 }finally{f.dom.window.close();}
});
test('tema oficial dinâmico claro/escuro, botões nativos e paginação vazia somente',async()=>{
 const f=fixture();try{await tick();const d=f.dom.window.document,root=d.querySelector('#sei-organizador');d.documentElement.style.setProperty('--infra-esquema-cor-barra-sistema','#111111');await tick();assert.equal(root.style.getPropertyValue('--so-theme-bg'),'rgb(17,17,17)');assert.equal(root.style.getPropertyValue('--so-theme-fg'),'#ffffff');d.documentElement.style.setProperty('--infra-esquema-cor-barra-sistema','#eeeeee');await tick();assert.equal(root.style.getPropertyValue('--so-theme-fg'),'#000000');assert.ok(d.querySelector('.so-toolbar button').classList.contains('infraButton'));const p=d.querySelector('#divInfraAreaPaginacaoSuperior');assert.ok(p.classList.contains('so-empty-pagination'));p.insertAdjacentHTML('beforeend','<button type="button">Próxima página</button>');await tick();assert.equal(p.classList.contains('so-empty-pagination'),false);assert.equal(p.textContent,'Próxima página');assert.ok(d.querySelector('#frmRelBlocoProtocoloLista').classList.contains('so-block-page'));
 }finally{f.dom.window.close();}
});
test('foreground do identificador SEI branco com contraste e fallback claro',async()=>{
 const f=fixture();try{await tick();const d=f.dom.window.document,root=d.querySelector('#sei-organizador');d.body.insertAdjacentHTML('afterbegin','<nav id="navInfraBarraNavegacao"><span id="spnInfraIdentificacaoSistema" style="color:white">Identificador</span></nav>');d.documentElement.style.setProperty('--infra-esquema-cor-barra-sistema','#0494c7');await tick();assert.equal(root.style.getPropertyValue('--so-theme-fg'),'rgb(255,255,255)');assert.notEqual(root.style.getPropertyValue('--so-theme-bg'),'rgb(4,148,199)');assert.equal(root.style.getPropertyValue('--so-button-fg'),'#495057');d.documentElement.style.setProperty('--infra-esquema-cor-barra-sistema','#eeeeee');await tick();assert.equal(root.style.getPropertyValue('--so-theme-fg'),'#000000');}finally{f.dom.window.close();}
});



