import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
const source=readFileSync(new URL('../extension/content.js',import.meta.url),'utf8');
const tick=()=>new Promise(r=>setTimeout(r,20));
const row=id=>`<tr id="trPos0"><td><input type="checkbox" id="chkInfraItem${id}"></td><td data-label="Seq.">${id}</td><td data-label="Processo"><a href="?id_procedimento=${id}">Processo fictício</a></td><td data-label="Tipo">Tipo fictício</td><td data-label="Anotações">Anotação nativa</td><td data-label="Ações"><a href="#">Anotações</a></td></tr>`;
function fixture(action='rel_bloco_protocolo_listar',origin='bloco_interno_listar',heading='Processos do Bloco Interno fictício',nativeFields=''){
 const dom=new JSDOM(`<h1>${heading}</h1><a id="lnkUsuarioSistema" title="Pessoa Teste (teste/SEPM)" href="?infra_unidade_atual=1"></a><form id="frmRelBlocoProtocoloLista">${nativeFields}<div id="divInfraAreaPaginacaoSuperior"></div><div id="divInfraAreaTabela"><table id="tblProtocolosBlocos"><tr><th></th><th>Seq.</th><th>Processo</th><th>Tipo</th><th>Anotações</th><th>Ações</th></tr>${row('100')}${row('200')}</table></div><button id="native" type="button">Original</button></form>`,{url:`https://sei.rj.gov.br/sei/controlador.php?acao=${action}&acao_origem=${origin}&id_bloco=2`,runScripts:'outside-only'});
 Object.defineProperty(dom.window.document,'hidden',{value:false,configurable:true});let sync;const nativeInterval=dom.window.setInterval.bind(dom.window);dom.window.setInterval=(callback,delay,...args)=>{if(delay===10000)sync=callback;return nativeInterval(callback,delay,...args);};let offline=false;const calls=[];dom.window.chrome={runtime:{sendMessage:async msg=>{calls.push(msg);if(msg.history)return {data:['create','delete','assign','unassign','rename','undo'].map(type=>({version:1,time:'2026-10-01T12:00:00Z',actor:{login:'teste'},action:{type,tabName:'Assunto',processIds:['100']}}))};return offline?{error:'Falha simulada'}:{data:{version:1,tabs:[{id:'a',name:'Assunto'}],assignments:{'100':['a']}}};}}};
 dom.window.SEI_ORGANIZADOR_CONFIG={serviceUrl:'https://ext.5cpa.com.br',unitId:'1'};dom.window.eval(readFileSync(new URL('../extension/history.js',import.meta.url),'utf8'));dom.window.eval(readFileSync(new URL('../extension/theme.js',import.meta.url),'utf8'));dom.window.eval(source);return {dom,calls,sync:()=>sync(),disconnect:()=>{offline=true;}};
}
test('Descrição e pesquisa compartilham linha preservando campos nativos e restauração ao sair',async()=>{
 const fields='<label id="lblDescricao" for="txtDescricao">Descrição:</label><br id="description-break"><input id="txtDescricao" value="Bloco de teste" disabled><div id="divInfraAreaDados" style="height:5em"><label id="lblPalavrasPesquisa" for="txtPalavrasPesquisaRelBlocoProtocolo">Palavras-chave para pesquisa:</label><input id="txtPalavrasPesquisaRelBlocoProtocolo" value="consulta"></div>';
 const f=fixture('rel_bloco_protocolo_listar','bloco_interno_listar','Processos do Bloco Interno fictício',fields);try{await tick();const w=f.dom.window,d=w.document,form=d.querySelector('form'),description=d.querySelector('#txtDescricao'),search=d.querySelector('#txtPalavrasPesquisaRelBlocoProtocolo'),panel=d.querySelector('#divInfraAreaDados');
 assert.equal(d.querySelectorAll('.so-block-fields').length,1);assert.equal(d.querySelector('.so-block-fields').children.length,2);assert.equal(description.disabled,true);assert.equal(description.value,'Bloco de teste');assert.equal(search.value,'consulta');assert.equal(search.form,form);assert.equal(d.querySelector('#lblPalavrasPesquisa').control,search);assert.equal(d.querySelector('#lblDescricao').control,description);
 let inputEvents=0;search.addEventListener('input',()=>inputEvents++);search.value='novo filtro';search.dispatchEvent(new w.Event('input',{bubbles:true}));f.sync();await tick();assert.equal(inputEvents,1);assert.equal(d.querySelector('#txtPalavrasPesquisaRelBlocoProtocolo'),search);assert.equal(d.querySelectorAll('.so-block-fields').length,1);
 w.history.pushState({},'', '?acao=procedimento_trabalhar&id_bloco=2');w.dispatchEvent(new w.PopStateEvent('popstate'));await tick();assert.equal(d.querySelector('.so-block-fields'),null);assert.equal(description.parentElement,form);assert.equal(panel.parentElement,form);assert.equal(panel.getAttribute('style'),'height:5em');assert.equal(panel.classList.contains('so-block-field'),false);assert.equal(d.querySelector('#lblDescricao').nextElementSibling.id,'description-break');assert.equal(search.value,'novo filtro');
 }finally{f.dom.window.close();}
});
test('retorno nativo de exclusão mantém inicialização, colunas e cabeçalho sem aceitar outros tipos de bloco',async()=>{
 const f=fixture('rel_bloco_protocolo_listar','rel_bloco_protocolo_excluir');try{await tick();const d=f.dom.window.document;assert.ok(d.querySelector('#sei-organizador'));assert.equal(d.querySelector('[data-tab=general]').getAttribute('aria-selected'),'true');assert.equal(d.querySelectorAll('th[data-so-column]').length,2);assert.equal(d.querySelectorAll('.so-floating-header').length,8);assert.equal(d.querySelectorAll('.so-copy-number').length,2);assert.ok(f.calls.length>0);}finally{f.dom.window.close();}
 const unrelated=fixture('rel_bloco_protocolo_listar','bloco_assinatura_listar','Processos do Bloco de Assinatura');try{await tick();assert.equal(unrelated.dom.window.document.querySelector('#sei-organizador'),null);assert.equal(unrelated.calls.length,0);}finally{unrelated.dom.window.close();}
});
test('lista interna independe da origem de retorno, mas nunca assume página de processo',async()=>{
 for(const origin of ['rel_bloco_protocolo_alterar','rel_bloco_protocolo_listar','outra_origem_nativa','']){const f=fixture('rel_bloco_protocolo_listar',origin);try{await tick();const d=f.dom.window.document;assert.ok(d.querySelector('#sei-organizador'));assert.equal(d.querySelectorAll('th[data-so-column]').length,2);assert.equal(d.querySelectorAll('.so-copy-number').length,2);}finally{f.dom.window.close();}}
 const process=fixture('procedimento_trabalhar','rel_bloco_protocolo_listar','Processo fictício');try{await tick();const d=process.dom.window.document;assert.equal(d.querySelector('#sei-organizador'),null);assert.equal(d.querySelectorAll('[data-so-column],.so-floating-header,.so-copy-number').length,0);assert.equal(d.querySelector('form').classList.contains('so-block-page'),false);assert.equal(process.calls.length,0);}finally{process.dom.window.close();}
});
test('recupera barra removida, tabela substituída e retorno do histórico sem duplicar interface',async()=>{
 const f=fixture();try{await tick();const w=f.dom.window,d=w.document;const root=d.querySelector('#sei-organizador');root.remove();await tick();assert.equal(d.querySelector('#sei-organizador'),root);
 const previous=d.querySelector('table');previous.outerHTML=`<table id="tblProtocolosBlocos"><tr><th></th><th>Seq.</th><th>Processo</th><th>Tipo</th><th>Anotações</th><th>Ações</th></tr>${row('300')}</table>`;await tick();await tick();const next=d.querySelector('table');assert.equal(d.querySelectorAll('#sei-organizador').length,1);assert.equal(next.querySelectorAll('th[data-so-column]').length,2);assert.equal(next.querySelectorAll('.so-copy-number').length,1);assert.equal(next.querySelectorAll('.so-status-marker').length,1);
 w.dispatchEvent(new w.PageTransitionEvent('pagehide',{persisted:true}));assert.equal(d.querySelector('#sei-organizador'),null);w.dispatchEvent(new w.PageTransitionEvent('pageshow',{persisted:true}));await tick();await tick();assert.equal(d.querySelectorAll('#sei-organizador').length,1);assert.equal(next.querySelectorAll('th[data-so-column]').length,2);assert.equal(next.querySelectorAll('.so-copy-number').length,1);
 w.history.pushState({},'', '?acao=procedimento_trabalhar&id_bloco=2');w.dispatchEvent(new w.PopStateEvent('popstate'));await tick();assert.equal(d.querySelector('#sei-organizador'),null);assert.equal(next.querySelectorAll('[data-so-column],.so-copy-number,.so-floating-header').length,0);assert.equal(next.classList.contains('so-organized-table'),false);
 w.history.pushState({},'', '?acao=rel_bloco_protocolo_listar&id_bloco=2');w.dispatchEvent(new w.PopStateEvent('popstate'));await tick();await tick();assert.equal(d.querySelectorAll('#sei-organizador').length,1);assert.ok(next.querySelector('.so-copy-number'));
 }finally{f.dom.window.close();}
});
test('inicia quando lista chega depois do script e não depende de contêiner opcional',async()=>{
 const f=fixture('procedimento_trabalhar');try{await tick();const w=f.dom.window,d=w.document;d.querySelector('#divInfraAreaPaginacaoSuperior').remove();const container=d.querySelector('#divInfraAreaTabela'),table=d.querySelector('table');container.replaceWith(table);
 w.history.pushState({},'', '?acao=rel_bloco_protocolo_listar&id_bloco=2');d.querySelector('h1').textContent='Processos do Bloco Interno recuperado';await tick();await tick();assert.ok(d.querySelector('#sei-organizador'));assert.equal(d.querySelectorAll('.so-copy-number').length,2);assert.equal(d.querySelectorAll('#so-history-panel').length,1);
 }finally{f.dom.window.close();}
});
test('colunas próprias idempotentes, múltiplos assuntos, novas linhas e estado desconhecido',async()=>{
 const f=fixture();try{await tick();const w=f.dom.window,d=w.document,t=d.querySelector('table');const first=d.querySelector('#chkInfraItem100').closest('tr');
 let state={version:2,tabs:[{id:'a',name:'Assunto'},{id:'b',name:'Outra'},{id:'c',name:'<Terceira>'}],assignments:{100:['a','b','c']},statuses:{100:'follow'}};
 w.chrome.runtime.sendMessage=async()=>({data:state});const click=name=>Array.from(d.querySelectorAll('#sei-organizador button')).find(b=>b.textContent===name).click();f.sync();await tick();
 assert.deepEqual(Array.from(t.rows[0].cells).map(c=>c.textContent),['','Seq.','Processo','Tipo','Assunto','Status','Anotações','Ações']);
 assert.equal(first.cells.length,8);assert.equal(first.querySelector('[data-so-column=subject]').textContent,'Assuntomais 2');assert.match(first.querySelector('[data-so-column=subject]').getAttribute('aria-label'),/<Terceira>/);assert.equal(first.querySelector('[data-so-column=subject] terceira'),null);
 const note=first.querySelector('[data-label="Anotações"]'),nativeAction=first.querySelector('[data-label="Ações"] a');assert.equal(note.textContent,'Anotação nativa');assert.equal(note.querySelector('button'),null);assert.match(first.querySelector('[data-so-column=status]').textContent,/Acompanhar/);
 let nativeClicks=0;nativeAction.addEventListener('click',()=>nativeClicks++);nativeAction.click();assert.equal(nativeClicks,1);
 t.insertAdjacentHTML('beforeend',row('300')+'<tr><td colspan="6">Paginação nativa</td></tr>');await tick();f.sync();await tick();assert.equal(t.querySelectorAll('th[data-so-column]').length,2);assert.equal(d.querySelector('#chkInfraItem300').closest('tr').cells.length,8);assert.equal(t.querySelector('[colspan]').colSpan,8);assert.equal(t.querySelectorAll('.so-status-marker').length,3);
 click('Assunto');assert.match(d.querySelector('.so-viewing').textContent,/^Visualizando: Assunto/);assert.equal(d.querySelector('[data-tab=general]').getAttribute('aria-selected'),'false');click('Geral');assert.match(d.querySelector('.so-viewing').textContent,/^Visualizando: todos os processos/);assert.equal(first.querySelector('[data-so-column=subject]').textContent,'Assuntomais 2');
 w.chrome.runtime.sendMessage=async()=>({error:'Offline'});f.sync();await tick();assert.equal(first.querySelector('[data-so-column=subject]').textContent,'Não sincronizado');assert.match(first.querySelector('[data-so-column=status]').textContent,/indisponível/);assert.equal(d.querySelector('[data-tab=general]').getAttribute('aria-selected'),'true');assert.equal(nativeAction.isConnected,true);
 }finally{f.dom.window.close();}
});
test('Assunto aparece somente em Geral e alternância preserva Status, colgroup e paginação',async()=>{
 const f=fixture();try{await tick();const d=f.dom.window.document,t=d.querySelector('table');
 t.insertAdjacentHTML('afterbegin','<colgroup><col><col><col><col><col><col></colgroup>');t.insertAdjacentHTML('beforeend','<tr><td colspan="6">Paginação nativa</td></tr>');await tick();
 const click=name=>Array.from(d.querySelectorAll('[role=tab]')).find(b=>b.textContent===name).click();
 const check=count=>{assert.equal(t.rows[0].cells.length,count);assert.equal(t.querySelector('colgroup').children.length,count);assert.equal(t.querySelector('[colspan]').colSpan,count);for(const r of Array.from(t.rows).filter(r=>r.querySelector('input[type=checkbox]')))assert.equal(r.cells.length,count);assert.equal(t.querySelectorAll('.so-status-marker').length,3);};
 t.insertAdjacentHTML('beforeend',row('300'));await tick();check(8);
 for(let i=0;i<2;i++){for(const name of ['Assunto','Sem assunto']){click(name);await tick();check(7);assert.equal(t.querySelector('[data-so-column=subject]'),null);assert.equal(t.querySelectorAll('th[data-so-column=status]').length,1);}click('Geral');await tick();check(8);assert.equal(t.querySelectorAll('th[data-so-column=subject]').length,1);assert.equal(t.querySelector('#chkInfraItem100').closest('tr').querySelector('.so-subject-label').textContent,'Assunto');}
 click('Assunto');t.insertAdjacentHTML('beforeend',row('400'));await tick();assert.equal(t.querySelector('#chkInfraItem400').closest('tr').cells.length,7);assert.equal(t.querySelector('[data-so-column=subject]'),null);click('Geral');await tick();assert.equal(t.querySelector('#chkInfraItem400').closest('tr').cells.length,8);
 }finally{f.dom.window.close();}
});
test('cabeçalho original acompanha altura da barra e limite da tabela sem duplicar controles',async()=>{
 const f=fixture();try{await tick();const w=f.dom.window,d=w.document,t=d.querySelector('table'),header=t.rows[0],root=d.querySelector('#sei-organizador');
 const all=d.createElement('input');all.type='checkbox';all.id='native-select-all';header.cells[0].append(all);let clicks=0;all.addEventListener('click',()=>clicks++);
 let barBottom=120,tableTop=-300,tableBottom=1000;root.getBoundingClientRect=()=>({bottom:barBottom});t.getBoundingClientRect=()=>({top:tableTop,bottom:tableBottom});header.getBoundingClientRect=()=>({height:30});Object.defineProperty(header,'offsetTop',{value:0});
 const recalc=async()=>{w.dispatchEvent(new w.Event('scroll'));await tick();};await recalc();assert.equal(t.style.getPropertyValue('--so-table-header-shift'),'420px');
 barBottom=160;w.dispatchEvent(new w.Event('resize'));await tick();assert.equal(t.style.getPropertyValue('--so-table-header-shift'),'460px');
 tableBottom=180;await recalc();assert.equal(t.style.getPropertyValue('--so-table-header-shift'),'450px');tableTop=200;tableBottom=900;await recalc();assert.equal(t.style.getPropertyValue('--so-table-header-shift'),'0px');
 assert.equal(t.rows[0],header);assert.equal(d.querySelectorAll('#native-select-all').length,1);assert.equal(header.querySelectorAll('.so-floating-header').length,8);all.click();assert.equal(clicks,1);assert.equal(all.checked,true);
 }finally{f.dom.window.close();}
});
test('Geral, seleção oculta, linhas de outra página, privacidade e indisponibilidade',async()=>{
 const f=fixture();try{await tick();const d=f.dom.window.document;const buttons=()=>Array.from(d.querySelectorAll('#sei-organizador button'));const click=name=>buttons().find(b=>b.textContent===name).click();
 assert.ok(d.querySelector('#sei-organizador'));assert.equal(d.querySelector('#native').textContent,'Original');
 d.querySelector('#chkInfraItem200').checked=true;click('Assunto');assert.equal(d.querySelector('#chkInfraItem200').checked,false);assert.equal(d.querySelector('#chkInfraItem200').closest('tr').hidden,true);
 click('Geral');assert.equal(d.querySelector('#chkInfraItem200').closest('tr').hidden,false);
 click('Assunto');d.querySelector('#tblProtocolosBlocos').insertAdjacentHTML('beforeend',row('300'));await tick();assert.equal(d.querySelector('#chkInfraItem300').closest('tr').hidden,true);
 f.disconnect();f.sync();await tick();assert.equal(d.querySelector('#chkInfraItem300').closest('tr').hidden,false);assert.ok(Array.from(d.querySelectorAll('[role=status]')).some(e=>/Sem sincronização/.test(e.textContent)));assert.equal(buttons().find(b=>b.textContent==='+ Criar assunto').disabled,true);
 assert.ok(f.calls.every(c=>Object.keys(c).every(k=>['type','unit','block'].includes(k))));
 }finally{f.dom.window.close();}
});
test('não injeta no Controle de Processos',()=>{const f=fixture('procedimento_controlar');try{assert.equal(f.dom.window.document.querySelector('#sei-organizador'),null);assert.equal(f.calls.length,0);}finally{f.dom.window.close();}});
test('menu atribui somente alvo, mantém seleção alheia e respeita links/offline',async()=>{
 const f=fixture();try{await tick();const w=f.dom.window,d=w.document;const target=d.querySelector('#chkInfraItem200').closest('tr');const other=d.querySelector('#chkInfraItem100');other.checked=true;
 const open=element=>{const e=new w.MouseEvent('contextmenu',{bubbles:true,cancelable:true,clientX:9999,clientY:9999});element.dispatchEvent(e);return e;};
 assert.equal(open(target.querySelector('a')).defaultPrevented,false);assert.equal(d.querySelector('[role=menu]'),null);
 assert.equal(open(target).defaultPrevented,true);assert.ok(d.querySelector('[role=menu]'));assert.equal(d.activeElement.getAttribute('role'),'menuitemcheckbox');d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(d.querySelector('[role=menu]'),null);
 target.dispatchEvent(new w.KeyboardEvent('keydown',{key:'F10',shiftKey:true,bubbles:true,cancelable:true}));assert.ok(d.querySelector('[role=menu]'));w.dispatchEvent(new w.Event('scroll'));assert.equal(d.querySelector('[role=menu]'),null);
 open(target);d.querySelector('#native').dispatchEvent(new w.Event('pointerdown',{bubbles:true}));assert.equal(d.querySelector('[role=menu]'),null);
 open(target);d.querySelector('[role=menuitemcheckbox]').click();await tick();const op=f.calls.find(c=>c.body);assert.deepEqual(Array.from(op.body.action.processIds),['200']);assert.equal(other.checked,true);assert.equal(d.querySelector('[role=menu]'),null);
 f.disconnect();f.sync();await tick();assert.equal(open(target).defaultPrevented,false);assert.equal(d.querySelector('[role=menu]'),null);
 }finally{f.dom.window.close();}
});
test('histórico aplica cores por ação e mantém rótulos textuais',async()=>{
 const f=fixture();try{await tick();const d=f.dom.window.document;Array.from(d.querySelectorAll('button')).find(b=>b.textContent==='Histórico').click();await tick();for(const type of ['create','delete','assign','unassign','rename','undo'])assert.ok(d.querySelector('.so-history-'+type)?.textContent.includes('teste'));assert.equal(d.querySelectorAll('.so-history-entry').length,6);}finally{f.dom.window.close();}
});
test('menu reflete múltiplos vínculos e retira somente processo alvo',async()=>{
 const f=fixture();try{await tick();const w=f.dom.window,d=w.document;let state={version:2,tabs:[{id:'a',name:'Assunto'},{id:'b',name:'Outra'},{id:'c',name:'Livre'}],assignments:{100:['a','b'],200:['a']}};
 w.chrome.runtime.sendMessage=async msg=>{f.calls.push(msg);if(msg.body){const op=msg.body.action;assert.equal(op.type,'unassign');assert.equal(op.tabId,'b');assert.deepEqual(Array.from(op.processIds),['100']);state={...state,version:3,assignments:{100:['a'],200:['a']}};}return {data:state};};
 f.sync();await tick();d.querySelector('#chkInfraItem200').checked=true;const target=d.querySelector('#chkInfraItem100').closest('tr');
 const open=()=>target.dispatchEvent(new w.MouseEvent('contextmenu',{bubbles:true,cancelable:true}));open();let entries=Array.from(d.querySelectorAll('[role=menuitemcheckbox]'));assert.deepEqual(entries.map(b=>b.getAttribute('aria-checked')),['true','true','false']);assert.match(entries[0].textContent,/Retirar de Assunto/);assert.match(entries[2].textContent,/Atribuir a Livre/);
 d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));Array.from(d.querySelectorAll('[role=tab]')).find(b=>b.textContent==='Outra').click();open();entries=Array.from(d.querySelectorAll('[role=menuitemcheckbox]'));entries[1].click();await tick();assert.equal(d.querySelector('#chkInfraItem200').checked,false);assert.equal(target.hidden,true);Array.from(d.querySelectorAll('[role=tab]')).find(b=>b.textContent==='Geral').click();assert.equal(target.hidden,false);assert.equal(d.querySelector('[role=menu]'),null);open();entries=Array.from(d.querySelectorAll('[role=menuitemcheckbox]'));assert.deepEqual(entries.map(b=>b.getAttribute('aria-checked')),['true','false','false']);assert.match(entries[1].textContent,/Atribuir a Outra/);assert.deepEqual(state.assignments[200],['a']);
 }finally{f.dom.window.close();}
});
test('Sem assunto virtual, contagens locais, vínculos obsoletos, sincronização e offline',async()=>{
 const f=fixture();try{await tick();const w=f.dom.window,d=w.document;let state={version:2,tabs:[{id:'a',name:'Assunto'},{id:'b',name:'Outra'}],assignments:{100:['a','b'],200:['obsoleta']}};
 w.chrome.runtime.sendMessage=async msg=>{f.calls.push(msg);if(msg.body){const op=msg.body.action;const remaining=(state.assignments[op.processIds[0]]||[]).filter(id=>id!==op.tabId);state={...state,version:state.version+1,assignments:{...state.assignments,[op.processIds[0]]:remaining}};}return {data:state};};
 const click=name=>Array.from(d.querySelectorAll('#sei-organizador button')).find(b=>b.textContent===name).click();const tab=name=>Array.from(d.querySelectorAll('[role=tab]')).find(b=>b.textContent===name);
 f.sync();await tick();assert.equal(tab('Geral').getAttribute('aria-selected'),'true');assert.equal(tab('Geral').dataset.count,undefined);assert.equal(tab('Assunto').dataset.count,'1');assert.equal(tab('Outra').dataset.count,'1');assert.equal(tab('Sem assunto').dataset.count,'1');
 d.querySelector('#chkInfraItem100').checked=true;click('Sem assunto');assert.equal(d.querySelector('#chkInfraItem100').checked,false);assert.equal(d.querySelector('#chkInfraItem100').closest('tr').hidden,true);assert.equal(d.querySelector('#chkInfraItem200').closest('tr').hidden,false);assert.equal(Array.from(d.querySelectorAll('button')).some(b=>b.textContent==='Renomear'),false);assert.equal(d.querySelectorAll('.so-toolbar select').length,1);assert.equal(d.querySelector('.so-filter-notice'),null);assert.match(tab('Geral').title,/Mostrar todos/);
 d.querySelector('table').insertAdjacentHTML('beforeend',row('300'));await tick();assert.equal(tab('Geral').dataset.count,undefined);assert.equal(tab('Sem assunto').dataset.count,'2');assert.equal(d.querySelector('#chkInfraItem300').closest('tr').hidden,false);
 click('Geral');assert.equal(d.querySelectorAll('tr[hidden]').length,0);const target=d.querySelector('#chkInfraItem100').closest('tr');const open=()=>target.dispatchEvent(new w.MouseEvent('contextmenu',{bubbles:true,cancelable:true}));open();Array.from(d.querySelectorAll('[role=menuitemcheckbox]')).find(b=>b.textContent.includes('Assunto')).click();await tick();assert.equal(tab('Sem assunto').dataset.count,'2');open();Array.from(d.querySelectorAll('[role=menuitemcheckbox]')).find(b=>b.textContent.includes('Outra')).click();await tick();assert.equal(tab('Sem assunto').dataset.count,'3');click('Sem assunto');assert.equal(target.hidden,false);
 w.chrome.runtime.sendMessage=async()=>({error:'Falha simulada'});f.sync();await tick();assert.equal(tab('Geral').getAttribute('aria-selected'),'true');assert.equal(tab('Sem assunto').disabled,true);assert.equal(tab('Sem assunto').dataset.count,'—');assert.match(d.querySelector('.so-summary').textContent,/classificações desconhecidas/);assert.equal(d.querySelectorAll('tr[hidden]').length,0);
 }finally{f.dom.window.close();}
});
test('histórico alterna, preserva estado após sync e ignora respostas atrasadas',async()=>{
 const f=fixture();try{await tick();const d=f.dom.window.document;const click=name=>Array.from(d.querySelectorAll('button')).find(b=>b.textContent===name).click();const toggle=()=>d.querySelector('[aria-controls="so-history-panel"]');const panel=d.querySelector('#so-history-panel');
 click('Histórico');await tick();assert.equal(toggle().getAttribute('aria-expanded'),'true');assert.equal(panel.hidden,false);f.sync();await tick();assert.equal(toggle().getAttribute('aria-expanded'),'true');assert.equal(toggle().textContent,'Fechar histórico');assert.equal(panel.querySelectorAll('button').length,0);click('Fechar histórico');assert.equal(panel.hidden,true);click('Histórico');await tick();assert.equal(panel.hidden,false);click('Fechar histórico');assert.equal(toggle().getAttribute('aria-expanded'),'false');f.sync();await tick();assert.equal(panel.hidden,true);
 let resolve,count=0;const original=f.dom.window.chrome.runtime.sendMessage;f.dom.window.chrome.runtime.sendMessage=msg=>msg.history?(count++,new Promise(r=>{resolve=r;})):original(msg);
 click('Histórico');click('Fechar histórico');resolve({data:[]});await tick();assert.equal(panel.hidden,true);assert.equal(panel.children.length,0);assert.equal(toggle().getAttribute('aria-expanded'),'false');
 click('Histórico');click('Fechar histórico');click('Histórico');assert.equal(count,2);resolve({data:[]});await tick();assert.equal(panel.hidden,false);assert.equal(panel.querySelectorAll('button').length,0);assert.equal(toggle().textContent,'Fechar histórico');assert.ok(!panel.textContent.includes('Carregando'));
 }finally{f.dom.window.close();}
});
test('copiar usa somente número do link, preserva controles e não duplica em mutações',async()=>{
 const f=fixture();try{await tick();const w=f.dom.window,d=w.document;const link=d.querySelector('a[href*="id_procedimento=100"]');link.textContent='  SEI-123456/123456/2026 \n ';const values=[];Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async value=>{values.push(value);}},configurable:true});
 const copy=link.nextElementSibling;assert.equal(copy.type,'button');assert.equal(copy.getAttribute('aria-label'),'Copiar número do processo');d.querySelector('#chkInfraItem100').checked=true;let bubbled=0;link.closest('tr').addEventListener('click',()=>bubbled++);copy.click();await tick();assert.deepEqual(values,['SEI-123456/123456/2026']);assert.equal(bubbled,0);assert.equal(d.querySelector('#chkInfraItem100').checked,true);assert.equal(copy.nextElementSibling.textContent,'Copiado');assert.equal(d.querySelector('[role=menu]'),null);
 Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async()=>{throw new Error('Denied');}},configurable:true});copy.click();await tick();assert.match(copy.nextElementSibling.textContent,/Não foi possível copiar/);assert.ok(!copy.nextElementSibling.textContent.includes('Copiado'));
 d.querySelector('table').insertAdjacentHTML('beforeend',row('300'));await tick();assert.equal(d.querySelectorAll('.so-copy-number').length,3);f.sync();await tick();assert.equal(d.querySelectorAll('.so-copy-number').length,3);assert.equal(d.querySelectorAll('.so-copy-feedback').length,3);assert.equal(link.textContent.trim(),'SEI-123456/123456/2026');
 }finally{f.dom.window.close();}
});
test('status na coluna própria: manual, alvo correto, sync, sem assunto e offline',async()=>{
 const f=fixture();try{await tick();const w=f.dom.window,d=w.document;const target=d.querySelector('#chkInfraItem200').closest('tr');target.querySelector('[data-label="Anotações"]').innerHTML='<span id="note">Anotação preservada</span>';target.querySelector('[data-label="Ações"] a').id='native-note';
 let state={version:2,tabs:[{id:'a',name:'Assunto'}],assignments:{100:['a']},statuses:{}};w.chrome.runtime.sendMessage=async msg=>{f.calls.push(msg);if(msg.body){const a=msg.body.action;assert.equal(a.type,'status');assert.deepEqual(Array.from(a.processIds),['200']);state={...state,version:3,statuses:{200:a.status}};}return {data:state};};
 const click=name=>Array.from(d.querySelectorAll('#sei-organizador button')).find(b=>b.textContent===name).click();f.sync();await tick();let marker=target.querySelector('.so-status-marker');assert.ok(marker.textContent.includes('Sem status'));marker.click();const option=Array.from(d.querySelectorAll('[role=menuitemradio]')).find(b=>b.textContent.includes('Urgente'));assert.ok(option);option.click();await tick();assert.match(marker.textContent,/Urgente/);assert.equal(d.querySelector('#note').textContent,'Anotação preservada');assert.ok(d.querySelector('#native-note'));click('Sem assunto');assert.equal(target.hidden,false);assert.equal(target.querySelectorAll('.so-status-marker').length,1);
 state={...state,version:4,statuses:{200:'follow'}};f.sync();await tick();assert.match(marker.textContent,/Acompanhar/);w.chrome.runtime.sendMessage=async()=>({error:'Falha simulada'});f.sync();await tick();assert.match(marker.textContent,/Status indisponível/);assert.equal(marker.disabled,true);assert.equal(target.hidden,false);
 }finally{f.dom.window.close();}
});
test('toolbar mantém todos comandos visíveis e histórico separado da barra sticky',async()=>{
 const f=fixture();try{await tick();const d=f.dom.window.document;assert.equal(d.querySelector('.so-options'),null);const toolbar=d.querySelector('.so-toolbar');for(const label of ['+ Criar assunto','Histórico'])assert.ok(Array.from(toolbar.querySelectorAll('button')).some(b=>b.textContent===label));assert.ok(toolbar.querySelector('.so-status-filter'));assert.ok(!Array.from(toolbar.querySelectorAll('button')).some(b=>b.textContent==='Atualizar'));assert.ok(!toolbar.textContent.includes('Atribuir selecionados'));assert.ok(!toolbar.textContent.includes('Retirar classificação'));assert.ok(!d.querySelector('#sei-organizador').contains(d.querySelector('#so-history-panel')));assert.equal(d.querySelector('#sei-organizador').style.getPropertyValue('--so-sticky-top'),'0px');
 }finally{f.dom.window.close();}
});
test('tema oficial dinâmico claro/escuro, botões nativos e paginação vazia somente',async()=>{
 const f=fixture();try{await tick();const d=f.dom.window.document,root=d.querySelector('#sei-organizador');d.documentElement.style.setProperty('--infra-esquema-cor-barra-sistema','#111111');await tick();assert.equal(root.style.getPropertyValue('--so-theme-bg'),'rgb(17,17,17)');assert.equal(root.style.getPropertyValue('--so-theme-fg'),'#ffffff');d.documentElement.style.setProperty('--infra-esquema-cor-barra-sistema','#eeeeee');await tick();assert.equal(root.style.getPropertyValue('--so-theme-fg'),'#000000');assert.ok(d.querySelector('.so-toolbar button').classList.contains('infraButton'));const p=d.querySelector('#divInfraAreaPaginacaoSuperior');assert.ok(p.classList.contains('so-empty-pagination'));p.insertAdjacentHTML('beforeend','<button type="button">Próxima página</button>');await tick();assert.equal(p.classList.contains('so-empty-pagination'),false);assert.equal(p.textContent,'Próxima página');assert.ok(d.querySelector('#frmRelBlocoProtocoloLista').classList.contains('so-block-page'));
 }finally{f.dom.window.close();}
});
test('Assunto clicável abre vínculos e devolve foco sem alterar controles nativos',async()=>{
 const f=fixture();try{await tick();const w=f.dom.window,d=w.document,b=d.querySelector('.so-subject-label');assert.equal(b.tagName,'BUTTON');assert.equal(b.getAttribute('aria-haspopup'),'menu');b.click();assert.ok(d.querySelector('[role=menuitemcheckbox]'));assert.equal(d.querySelector('#chkInfraItem100').checked,false);d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(d.activeElement,b);b.dispatchEvent(new w.KeyboardEvent('keydown',{key:'F10',shiftKey:true,bubbles:true,cancelable:true}));assert.ok(d.querySelector('[role=menu]'));f.disconnect();f.sync();await tick();assert.equal(d.querySelector('.so-subject-label').disabled,true);}finally{f.dom.window.close();}
});

test('status combina assunto, contagens locais, limpeza e indisponibilidade',async()=>{
 const f=fixture();try{await tick();const w=f.dom.window,d=w.document;let state={version:3,tabs:[{id:'a',name:'Assunto'}],assignments:{100:['a']},statuses:{100:'urgent'}};w.chrome.runtime.sendMessage=async()=>({data:state});const click=name=>Array.from(d.querySelectorAll('#sei-organizador button')).find(b=>b.textContent===name).click();f.sync();await tick();const choose=value=>{const s=d.querySelector('.so-status-filter');s.value=value;s.dispatchEvent(new w.Event('change'));};d.querySelector('#chkInfraItem200').checked=true;choose('urgent');assert.equal(d.querySelector('#chkInfraItem200').checked,false);assert.equal(d.querySelector('#chkInfraItem200').closest('tr').hidden,true);assert.match(d.querySelector('.so-viewing').textContent,/Urgente.*1\/2/);assert.equal(d.querySelector('[data-tab=__unassigned__]').dataset.count,'0');click('Sem assunto');assert.equal(d.querySelectorAll('tr[hidden]').length,2);choose('none');assert.equal(d.querySelectorAll('tr[hidden]').length,1);assert.match(d.querySelector('.so-status-filter option[value=none]').textContent,/\(1\)/);assert.ok(!Array.from(d.querySelectorAll('.so-toolbar button')).some(b=>b.textContent==='Limpar filtros'));click('Geral');choose('all');assert.equal(d.querySelectorAll('tr[hidden]').length,0);choose('urgent');state={version:4,tabs:state.tabs,assignments:state.assignments};f.sync();await tick();assert.equal(d.querySelector('.so-status-filter').disabled,true);assert.equal(d.querySelector('.so-status-filter').value,'all');assert.match(d.querySelector('.so-viewing').textContent,/Status indisponível/);assert.equal(d.querySelectorAll('tr[hidden]').length,0);}finally{f.dom.window.close();}
});

test('histórico mostra nome completo e desfazer somente próprio com confirmação e reconsulta',async()=>{
 const f=fixture();try{await tick();const w=f.dom.window,d=w.document;let version=5,posts=0,accept=false,blocked=false,reversed=false,confirmation='';
 const records=()=>[...(reversed?[{id:93,version,time:'2026-10-01T12:30:00Z',actor:{login:'teste',org:'SEPM'},action:{type:'undo',historyId:91},undoable:false}]:[]),{id:92,version:5,time:'2026-10-01T12:00:00Z',actor:{name:'Outro Colega',login:'colega',org:'SEPM'},action:{type:'status',status:'urgent',processIds:['200']},undoable:true},{id:91,version:4,time:'2026-10-01T11:00:00Z',actor:{name:'Pessoa Teste Completa',login:'teste',org:'SEPM'},action:{type:'assign',tabName:'Pasta',processIds:['100']},undoable:!blocked&&!reversed,undoReason:blocked?'Alteração posterior no mesmo campo':undefined}];
 w.confirm=text=>{confirmation=text;return accept;};w.chrome.runtime.sendMessage=async msg=>{if(msg.history)return {data:records()};if(msg.body){posts++;assert.equal(msg.body.action.historyId,91);assert.equal(msg.body.version,version);version++;reversed=true;}return {data:{version,tabs:[{id:'a',name:'Pasta'}],assignments:{100:['a']},statuses:{}}};};
 const toggle=()=>d.querySelector('[aria-controls=so-history-panel]');toggle().click();await tick();assert.equal(d.querySelector('.so-toolbar').textContent.includes('Desfazer'),false);assert.equal(d.querySelectorAll('.so-undo-record').length,1);assert.equal(d.querySelectorAll('.so-history-user')[1].title,'Pessoa Teste Completa (teste/SEPM)');assert.equal(d.querySelectorAll('.so-history-user')[0].textContent,'colega');
 const undo=()=>d.querySelector('.so-undo-record').click();undo();await tick();assert.match(confirmation,/Pessoa Teste Completa/);assert.match(confirmation,/Pasta/);assert.equal(posts,0);
 blocked=true;confirmation='';undo();await tick();assert.equal(confirmation,'');assert.equal(posts,0);assert.equal(d.querySelector('.so-undo-record'),null);
 blocked=false;toggle().click();toggle().click();await tick();accept=true;undo();await tick();assert.equal(posts,1);assert.equal(d.querySelector('#so-history-panel').hidden,false);assert.equal(d.querySelector('.so-undo-record'),null);assert.equal(d.querySelectorAll('.so-history-entry').length,3);assert.equal(d.querySelector('.so-history-reverted').textContent,' · Desfeita');
 }finally{f.dom.window.close();}
});
test('foreground do identificador SEI branco com contraste e fallback claro',async()=>{
 const f=fixture();try{await tick();const d=f.dom.window.document,root=d.querySelector('#sei-organizador');d.body.insertAdjacentHTML('afterbegin','<nav id="navInfraBarraNavegacao"><span id="spnInfraIdentificacaoSistema" style="color:white">Identificador</span></nav>');d.documentElement.style.setProperty('--infra-esquema-cor-barra-sistema','#0494c7');await tick();assert.equal(root.style.getPropertyValue('--so-theme-fg'),'rgb(255,255,255)');assert.notEqual(root.style.getPropertyValue('--so-theme-bg'),'rgb(4,148,199)');assert.equal(root.style.getPropertyValue('--so-button-fg'),'#495057');d.documentElement.style.setProperty('--infra-esquema-cor-barra-sistema','#eeeeee');await tick();assert.equal(root.style.getPropertyValue('--so-theme-fg'),'#000000');}finally{f.dom.window.close();}
});



