import http from 'node:http';
import {readFileSync} from 'node:fs';
const html=`<!doctype html><html lang="pt-BR"><meta charset="utf-8"><title>Fixture SEI Organizador</title><script>const theme=new URL(location.href).searchParams.get("theme");if(theme)document.documentElement.style.setProperty("--infra-esquema-cor-barra-sistema",theme);</script><style>:root{--infra-esquema-cor-barra-sistema:#0494c7}.infraButton{font:13px Arial;background:#fff;color:#495057;border:1px solid #666;border-radius:4px;padding:4.8px 9.6px}body{margin:0;font:14px Verdana}#divInfraBarraSistema{position:fixed;top:0;left:0;right:0;height:65px;box-sizing:border-box;padding:20px;background:#e8ece9;z-index:200}#divInfraAreaTelaD{position:relative;margin-top:65px;height:calc(100vh - 65px);overflow:auto;padding:20px;box-sizing:border-box}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #ddd;text-align:left}</style><link rel="stylesheet" href="/extension/content.css"><header id="divInfraBarraSistema">Cabeçalho SEI · fixture</header><nav id="navInfraBarraNavegacao" style="display:none"><span id="spnInfraIdentificacaoSistema" style="color:white">Identificador fictício</span></nav><div id="divInfraAreaTelaD"><a id="lnkUsuarioSistema" title="Pessoa Teste (teste/SEPM)" href="?infra_unidade_atual=1"></a><h1>Processos do bloco — fixture local</h1><form id="frmRelBlocoProtocoloLista"><div id="divInfraBarraComandosSuperior"><button class="infraButton" type="button">Botão nativo fictício</button></div><div id="divInfraAreaPaginacaoSuperior" style="height:30px;margin:5px 0"></div><table id="tblProtocolosBlocos"><tr><th></th><th>Seq.</th><th>Processo</th><th>Tipo</th><th>Anotações</th><th>Ações</th></tr>${Array.from({length:50},(_,i)=>i+1).map(id=>`<tr><td><input type="checkbox"></td><td>${id}</td><td><a href="?id_procedimento=${id}">SEI-123456/00000${id}/2026</a></td><td>Processo fictício</td><td data-label="Anotações">Anotação de demonstração</td><td><a href="#">Anotações</a></td></tr>`).join('')}</table></form></div><script>window.chrome={runtime:{sendMessage:async()=>({data:{version:1,tabs:[{id:'a',name:'Contratos'},{id:'b',name:'Correspondências'},{id:'c',name:'Demandas gerais'}],assignments:{1:['a'],2:['b']},statuses:{1:'urgent',2:'follow'}}})}};</script><script src="/extension/history.js"></script><script src="/extension/theme.js"></script><script src="/extension/content.js"></script></html>`;
http.createServer((req,res)=>{if(req.url.startsWith('/extension/')){const name=req.url.slice('/extension/'.length);if(!['content.css','content.js','history.js','theme.js'].includes(name)){res.writeHead(404).end();return;}res.setHeader('Content-Type',name.endsWith('.css')?'text/css':'application/javascript');res.end(readFileSync(new URL('../extension/'+name,import.meta.url)));}else{res.setHeader('Content-Type','text/html');res.end(html);}}).listen(8791,'127.0.0.1',()=>console.log('Fixture local pronta em 8791'));





